2025-07-31 22:20:23,953 [    INFO] Validating directory peds-protocol-combined/activities
Traceback (most recent call last):
  File "/Users/yibeichen/micromamba/envs/reproschema/bin/reproschema", line 8, in <module>
    sys.exit(main())
  File "/Users/yibeichen/micromamba/envs/reproschema/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/yibeichen/micromamba/envs/reproschema/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/yibeichen/micromamba/envs/reproschema/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/yibeichen/micromamba/envs/reproschema/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/yibeichen/micromamba/envs/reproschema/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/yibeichen/Documents/GitHub/reproschema-py/reproschema/cli.py", line 68, in validate
    result = validate(path)
  File "/Users/yibeichen/Documents/GitHub/reproschema-py/reproschema/validate.py", line 137, in validate
    stop, port = start_server()
  File "/Users/yibeichen/Documents/GitHub/reproschema-py/reproschema/utils.py", line 48, in start_server
    start, stop, port = simple_http_server(port=port, path=path)
  File "/Users/yibeichen/Documents/GitHub/reproschema-py/reproschema/utils.py", line 24, in simple_http_server
    server = HTTPServer((host, port), LoggingRequestHandler)
  File "/Users/yibeichen/micromamba/envs/reproschema/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/Users/yibeichen/micromamba/envs/reproschema/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/Users/yibeichen/micromamba/envs/reproschema/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
